### PR TITLE
fix several issues reported on issue #4

### PR DESCRIPTION
**Pull request by DavidBM**

### CODE REVIEW

**Comment by DavidBM** [comment]
@rhuffus @voro2038 @aegis22 Would any of you take a look to the code changes?

**Comment by GopherJ** [comment]
LGTM, BTW I think we can have `RsmqResult` which will make things simpler

**Comment by GopherJ** [comment]
I just checked nodejs rsmq seems they are using `{rsmqns}rt` instead of `{rsmqns}:rt`, shall we follow their decision to keep the compatibility?

https://github.com/smrchy/rsmq/blob/f41b7e4eceaec51ea91933f30c54db44e94c07af/index.js#L373

**Comment by DavidBM** [comment]
Good call. That makes sense, but the issue that I see is that they document it like: ` {rsmq.ns}:rt:{qname}` so I will ask them to choo to fix the documentation or the code.

**Comment by DavidBM** [comment]
I have added the RsmqResult type @GopherJ  :)

**Comment by DavidBM** [comment]
Reported to js rsmq library on https://github.com/smrchy/rsmq/issues/128

**Review by voro2038 — APPROVED** [review]

**Comment by DavidBM** [comment]
@GopherJ They didn't respond yet to https://github.com/smrchy/rsmq/issues/128 so I will merge this one. Feel free to change the code in your local copy. Once they respond I will make any required change.

**Pull request merged**
